### ISSUE TITLE
No issue just some praise

### ISSUE THREAD

**Issue by WebCrew** [XHiddenProjects/WebServerAI#1]
Unbelievable, you've really gone full throttle over the last few days. 

Geolocation, I didn't know about it before, is a new feature, great and **I love** what you've done with the **installation and extension documentation**. Even dummies like me can understand it well now. 

What I particularly like is the **installation with zip**, I find it much more pleasant and familiar than all the modern installation options like NPM, Node, Gulp and everything else that's out there, etc.

Great job man!

**Comment by XHiddenProjects** [comment]
@WebCrew Thank you very much. It's still in progress and I'll be updating the Wiki for python extensions.

**Comment by XHiddenProjects** [comment]
You can use your machine but you'll need to reconfigure everything to use it, but the compiler works.

**Comment by WebCrew** [comment]
I would so or so rather use the compiler than have to configure everything myself, which is why your compiler makes twice as much sense and saves us users a lot of extra work.

**Comment by XHiddenProjects** [comment]
Fair enough
